[package]
name = "show_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
pad = "0.1.6"
clap = { version = "4.0", features = ["derive"] }
tabled = "0.17.0"
comfy-table = "7.1.3"
sqlparser = "0.54.0"
prettytable-rs = "0.10.0"
regex = "1.11.1"
